version: "3.7"
services:
  frontend:
    build: ./frontend
    image: bttf-frontend:latest
    restart: always
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: nauMF5uY5KM89neV
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:8080
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: nauMF5uY5KM89neV
