version: "3.7"
services:
  tw:
    build: .
    image: tw2:latest
    restart: always
    environment:
      PICO_CTF_FLAG: flag{i_dont_want_to_say_goodbye__gets_me_every_time}
      MONGO_USER: rogue
      MONGO_PASS: clockbirddeskbearlimbo
    ports:
      - "8888:8888"
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rogue
      MONGO_INITDB_ROOT_PASSWORD: clockbirddeskbearlimbo
      MONGO_INITDB_DATABASE: blundertale
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
