version: "3.7"
services:
  tw:
    build: .
    image: tw3:latest
    restart: always
    environment:
      PICO_CTF_FLAG: flag{the_new_feature_where_you_manage_your_own_shelf_in_the_refrigerator_was_an_interesting_addition}
      MONGO_USER: rogue
      MONGO_PASS: clockbirddeskbearlimbo
    ports:
      - "8888:8888"
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rogue
      MONGO_INITDB_ROOT_PASSWORD: clockbirddeskbearlimbo
      MONGO_INITDB_DATABASE: blundertale
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
